update in UI job

diff --git a/ui/Jenkinsfile_developers b/ui/Jenkinsfile_developers
--- a/ui/Jenkinsfile_developers
+++ b/ui/Jenkinsfile_developers
@@ -127,13 +127,17 @@ stage('Deploy Approval - QA') {
 			id: 'userInput', message: 'Are you prepared to deploy?', parameters: [[$class: 'ChoiceParameterDefinition', choices: deployOptions, description: 'Approve/Disallow deployment', name: 'deploy-check']])
 	echo "userApprovalQAInput: ${userApprovalQAInput}"
 }
-
-if (qaReleaseCandidate.toBoolean() && userApprovalQAInput == 'yes') {
-	echo "Provided secondary approval for QA Release."
-} else if (qaReleaseCandidate.toBoolean() && userApprovalQAInput == 'no'){
-	echo "Didn't provide secondary approval for QA Release."
-	sh "exit 1" // this fails the stage
-	//return;
+try {
+	if (qaReleaseCandidate.toBoolean() && userApprovalQAInput == 'yes') {
+		echo "Provided secondary approval for QA Release."
+	} else if (qaReleaseCandidate.toBoolean() && userApprovalQAInput == 'no'){
+		echo "Didn't provide secondary approval for QA Release."
+		error 'FAIL'
+		//sh "exit 1" // this fails the stage
+		//return;
+	}
+} catch(error) {
+	currentBuild.result = 'SUCCESS'
 }
 //--------------------------------------------------------- QA SECONDARY APPROVAL CHECK END ---------------------------------------------------------
 
